image: java:8

stages:
  - build

build:
  stage: build
  script: ./gradlew clean build
  artifacts:
    paths:
      - web/admin/build/libs/web-admin-1.0.0-SNAPSHOT.jar
      - web/core/build/libs/web-core-1.0.0-SNAPSHOT.jar
      - web/build/libs/web-1.0.0-SNAPSHOT.jar
      - domain/build/libs/domain-1.0.0-SNAPSHOT-sources.jar
      - domain/build/libs/domain-1.0.0-SNAPSHOT.jar
      - util/build/libs/util-1.0.0-SNAPSHOT.jar
      - util/build/libs/util-1.0.0-SNAPSHOT-sources.jar
      - util-test/build/libs/util-test-1.0.0-SNAPSHOT.jar
      - test/build/libs/test-1.0.0-SNAPSHOT-sources.jar
      - test/build/libs/test-1.0.0-SNAPSHOT.jar
      - build/libs/mdu4j-1.0.0-SNAPSHOT.jar
