language: java
before_script:
    - wget http://services.gradle.org/distributions/gradle-2.14-bin.zip
    - unzip gradle-2.14-bin.zip
    - export GRADLE_HOME=$PWD/gradle-2.14
    - export PATH=$GRADLE_HOME/bin:$PATH